{% set name = "py-linux-ports" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2d7e6ecfe4458c9c087d414013ba2961a6a0541c5d441eea8d432d456a31ce01

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - PyLinuxPorts
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: "https://github.com/sujitmandal/py-linux-ports"
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: "Check Linux System Port's Status."
  doc_url: https://sujitmandal.github.io/py-linux-ports/
  dev_url: https://github.com/sujitmandal/py-linux-ports

extra:
  recipe-maintainers:
    - sujitmandal
